import { Client } from '../types/client';

// Static mock data for clients
export const mockClients: Client[] = [
  {
    id: '1',
    name: 'Acme Corporation',
    email: 'contact@acme.com',
    type: 'company',
    status: 'active',
    createdAt: new Date('2023-01-15'),
    updatedAt: new Date('2023-06-22'),
  },
  {
    id: '2',
    name: 'John Smith',
    email: 'john.smith@example.com',
    type: 'individual',
    status: 'active',
    createdAt: new Date('2023-02-10'),
    updatedAt: new Date('2023-05-18'),
  },
  {
    id: '3',
    name: 'TechStart Inc',
    email: 'info@techstart.com',
    type: 'company',
    status: 'pending',
    createdAt: new Date('2023-03-05'),
    updatedAt: new Date('2023-04-30'),
  },
  {
    id: '4',
    name: 'Sarah Johnson',
    email: 'sarah.j@example.com',
    type: 'individual',
    status: 'inactive',
    createdAt: new Date('2023-01-20'),
    updatedAt: new Date('2023-03-15'),
  },
  {
    id: '5',
    name: 'Global Solutions Ltd',
    email: 'contact@globalsolutions.com',
    type: 'company',
    status: 'active',
    createdAt: new Date('2022-12-01'),
    updatedAt: new Date('2023-07-10'),
  },
  {
    id: '6',
    name: 'Michael Brown',
    email: 'michael.b@example.com',
    type: 'individual',
    status: 'active',
    createdAt: new Date('2023-04-12'),
    updatedAt: new Date('2023-06-05'),
  },
  {
    id: '7',
    name: 'Innovate Systems',
    email: 'info@innovatesystems.com',
    type: 'company',
    status: 'pending',
    createdAt: new Date('2023-05-22'),
    updatedAt: new Date('2023-07-01'),
  },
  {
    id: '8',
    name: 'Emily Davis',
    email: 'emily.d@example.com',
    type: 'individual',
    status: 'inactive',
    createdAt: new Date('2023-02-28'),
    updatedAt: new Date('2023-04-10'),
  },
  {
    id: '9',
    name: 'Future Tech',
    email: 'contact@futuretech.com',
    type: 'company',
    status: 'active',
    createdAt: new Date('2022-11-15'),
    updatedAt: new Date('2023-07-15'),
  },
  {
    id: '10',
    name: 'Robert Wilson',
    email: 'robert.w@example.com',
    type: 'individual',
    status: 'active',
    createdAt: new Date('2023-03-18'),
    updatedAt: new Date('2023-06-28'),
  }
]; 